version: "3.5"
services:
  task-mongodb:
    # build: ./mongodb
    image: mongo:latest
    container_name: task-mongo
    command: mongod --auth
    ports:
      - 47017:27017
    environment:
      MONGO_INITDB_ROOT_PASSWORD: cGFzc3dvcmQxMjM=
      MONGO_INITDB_ROOT_USERNAME: user1
      MONGO_INITDB_DATABASE: notes
      MONGO_USERNAME: user1
      MONGO_PASSWORD: cGFzc3dvcmQxMjM=
      MONGO_DATABASE: notes
    volumes:
     - /etc/localtime:/etc/localtime
     - ./data/db:/data/db      
